apiVersion: nyl.niklasrosenstein.github.com/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: {{ .Values.namespace.name }}
spec:
  chart:
    repository: {{ .Values.argocd.chart.repository }}
    name: {{ .Values.argocd.chart.name }}
    version: {{ .Values.argocd.chart.version | quote }}
  values:
    {{- $defaultValues := .Values.argocd.values }}
    {{- $nylContainer := dict "name" "nyl-v1" "image" (printf "%s:%s" .Values.nyl.image.repository .Values.nyl.image.tag) "imagePullPolicy" .Values.nyl.image.pullPolicy "securityContext" .Values.nyl.securityContext "volumeMounts" (list (dict "mountPath" "/var/run/argocd" "name" "var-files") (dict "mountPath" "/home/argocd/cmp-server/plugins" "name" "plugins") (dict "mountPath" "/tmp" "name" "cmp-tmp")) "env" (list (dict "name" "NYL_CACHE_DIR" "value" .Values.nyl.env.NYL_CACHE_DIR)) }}
    {{- if .Values.nyl.envSecret.enabled }}
    {{- $_ := set $nylContainer "envFrom" (list (dict "secretRef" (dict "name" .Values.nyl.envSecret.name))) }}
    {{- end }}
    {{- $repoServerValues := dict "extraContainers" (list $nylContainer) "volumes" (list (dict "name" "cmp-tmp" "emptyDir" dict)) }}
    {{- $repoServerValues = merge $repoServerValues $defaultValues.repoServer }}
    {{- $mergedValues := merge (dict "repoServer" $repoServerValues) $defaultValues .Values.additionalValues }}
    {{- $mergedValues | toYaml | nindent 4 }}
