{{- if .Values.selfManage.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Values.namespace.name }}
spec:
  project: default
  source:
    repoURL: {{ .Values.selfManage.repoURL }}
    targetRevision: {{ .Values.selfManage.targetRevision }}
    path: {{ .Values.selfManage.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace.name }}
{{- end }}
