{{- if .Values.nyl.envSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nyl.envSecret.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.nyl.envSecret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
