apiVersion: nyl.io/v1
kind: StatefulSecret
metadata:
  name: postgres-password
stringData:
  PASSWORD: {{ randhex(32) }}
---
apiVersion: nyl.io/v1
kind: HelmChart
name: postgres
chart:
  repository: oci://registry-1.docker.io/bitnamicharts
  name: postgresql
  version: 15.5.16
values:
  auth:
    postgresPassword: {{ ref("Secret", "postgres-password", "PASSWORD") }}
