apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: {{ values.namespace }}
  labels:
    app: myapp
    environment: {{ values.environment }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: myapp
