//! CLI adapter for Kubernetes manifest rendering.

use clap::Args;
use kube::Client;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

use crate::{
    cli::commands::cluster::{load_cluster_kube_config, resolve_target_cluster, ResolvedTargetCluster},
    cli::namespace_resolution::{adjust_duplicate_keys_for_namespace_resolution, resolve_manifest_namespaces},
    config::ProjectConfig,
    git::is_argocd_env,
    kubernetes::{KubeRsClient, ResourceKey},
    render::{cache, prepare_manifests_for_output, RenderPathMode, RenderRequest, RenderSession},
    resources::Release,
    NylError, Result,
};

pub(crate) use crate::render::best_effort_parse_yaml_documents;
/// Common options for manifest rendering operations (render, apply, diff)
#[derive(Args, Debug, Clone)]
pub struct RenderOptions {
    /// Path to the manifest file
    #[arg(value_name = "FILE")]
    pub path: String,

    /// Filter top-level resources by kind (e.g., "ConfigMap", "Deployment") or apiVersion/kind (e.g., "apps/v1/Deployment").
    /// Note: Filter applies before expansion, so it only matches resources directly in the file, not resources generated by HelmChart or Component resources.
    #[arg(long, value_name = "KIND")]
    pub only_source_kind: Option<String>,

    /// Filter rendered manifests to only include specified kinds (post-render, comma-separated).
    /// Supports "Kind" or "apiVersion/Kind" format (e.g., "Deployment" or "apps/v1/Deployment").
    /// Mutually exclusive with --exclude-kind.
    #[arg(long, value_delimiter = ',', conflicts_with = "exclude_kind")]
    pub only_kind: Vec<String>,

    /// Filter rendered manifests to exclude specified kinds (post-render, comma-separated).
    /// Supports "Kind" or "apiVersion/Kind" format (e.g., "Secret" or "v1/Secret").
    /// Mutually exclusive with --only-kind.
    #[arg(long, value_delimiter = ',', conflicts_with = "only_kind")]
    pub exclude_kind: Vec<String>,

    /// GitOps target whose values and cluster capabilities are used
    #[arg(long)]
    pub target: Option<String>,

    /// Maximum evaluation depth for recursive resource expansion (default: 10)
    #[arg(long, default_value = "10")]
    pub max_depth: usize,

    /// Track parent resource information in annotations
    #[arg(long)]
    pub track_parent: bool,

    #[command(flatten)]
    pub cache: cache::RenderCacheArgs,
}

/// Render Kubernetes manifests to stdout
#[derive(Args, Debug)]
pub struct RenderArgs {
    #[command(flatten)]
    pub common: RenderOptions,

    /// Offline mode: never connect to Kubernetes
    #[arg(long)]
    pub offline: bool,

    /// Kubernetes version for targetless offline Helm rendering
    #[arg(long)]
    pub kube_version: Option<String>,

    /// Kubernetes API versions for targetless offline Helm rendering (comma-separated or repeated)
    #[arg(long, value_delimiter = ',')]
    pub kube_api_versions: Vec<String>,

    /// Kubernetes context override for live rendering
    #[arg(long)]
    pub context: Option<String>,
}

/// Output format for rendered manifests
#[derive(Debug, Clone, Copy)]
enum OutputFormat {
    Yaml,
    #[allow(dead_code)]
    Json,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClusterClientRequirement {
    OnDemand,
    Required,
}

/// Shared render preflight arguments for render/diff/apply commands.
pub struct RenderPreflightOptions<'a> {
    pub common: &'a RenderOptions,
    pub offline: bool,
    pub kube_version: Option<&'a str>,
    pub kube_api_versions: &'a [String],
    pub context_override: Option<&'a str>,
    pub cluster_client_requirement: ClusterClientRequirement,
    pub resolve_namespaces: bool,
    pub release_namespace_hint: Option<&'a str>,
    pub adjust_duplicate_keys: bool,
}

/// Shared render preflight output for render/diff/apply commands.
pub struct RenderPreflightResult {
    pub manifests: Vec<serde_json::Value>,
    pub release: Option<Release>,
    pub strip_empty_metadata_labels: bool,
    pub resolved_target: Option<ResolvedTargetCluster>,
    pub duplicates: HashMap<ResourceKey, usize>,
    pub kube_client: Option<KubeRsClient>,
    pub raw_client: Option<Client>,
}

#[allow(clippy::too_many_lines)]
pub async fn run_render_preflight(options: RenderPreflightOptions<'_>) -> Result<RenderPreflightResult> {
    let project_config = ProjectConfig::load_with_warning(None)?;
    let current_dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let project_root = project_config
        .file
        .as_deref()
        .and_then(Path::parent)
        .unwrap_or(&current_dir);
    let resolved_target = options
        .common
        .target
        .as_deref()
        .map(|name| resolve_target_cluster(project_root, name))
        .transpose()?;

    if resolved_target.is_some() && (options.kube_version.is_some() || !options.kube_api_versions.is_empty()) {
        return Err(NylError::config(
            "--kube-version and --kube-api-versions cannot be used with --target; the Cluster resource is authoritative",
        ));
    }
    let explicit_capabilities = match (options.kube_version, options.kube_api_versions.is_empty()) {
        (Some(version), false) if !version.trim().is_empty() => {
            Some((version.to_owned(), options.kube_api_versions.to_vec()))
        }
        _ => None,
    };
    let missing_capabilities_error = if options.offline {
        Some("Offline targetless Helm rendering requires --kube-version and --kube-api-versions".to_string())
    } else {
        Some(
            "Rendering Helm resources online requires --target; alternatively use --offline with --kube-version and --kube-api-versions"
                .to_string(),
        )
    };
    let mut session = RenderSession::for_cli(
        project_root,
        &project_config,
        resolved_target
            .as_ref()
            .map(|resolved| (&resolved.target, &resolved.cluster)),
        explicit_capabilities,
        missing_capabilities_error,
    )
    .await?;
    let render_cache = cache::RenderCache::new(project_root, options.common.cache.mode())?;
    let _cache_reporter = render_cache.reporter();
    session.set_cache(Some(render_cache));
    let path = Path::new(&options.common.path);
    let provenance_root = project_config
        .file
        .as_deref()
        .and_then(Path::parent)
        .or_else(|| path.is_absolute().then(|| path.parent()).flatten());
    let mut request = RenderRequest::new(path, provenance_root);
    request.path_mode = RenderPathMode::AsProvided;
    request.only_source_kind = options.common.only_source_kind.as_deref();
    request.max_depth = options.common.max_depth;
    request.track_parent = options.common.track_parent;
    request.expand_application_generators = true;
    request.strip_empty_metadata_labels_default = is_argocd_env();
    let rendered = session.render(request).await?;
    let strip_empty_metadata_labels = rendered.strip_empty_metadata_labels;
    let mut manifests = rendered.manifests;
    let release = rendered.release;
    let mut duplicates = rendered.duplicates;

    manifests = crate::cli::filter::filter_manifests_by_kind(
        manifests,
        &options.common.only_kind,
        &options.common.exclude_kind,
    )?;

    let should_initialize_clients = should_initialize_cluster_clients(
        options.offline,
        options.cluster_client_requirement,
        options.resolve_namespaces,
        &manifests,
        options.adjust_duplicate_keys,
    );

    let (kube_client, raw_client) = if should_initialize_clients {
        let resolved = resolved_target
            .as_ref()
            .ok_or_else(|| NylError::config("This operation requires --target so Nyl can select a trusted cluster"))?;
        let config = load_cluster_kube_config(&resolved.cluster, options.context_override).await?;
        let client = Client::try_from(config)?;
        (Some(KubeRsClient::from_client(client.clone()).await?), Some(client))
    } else {
        (None, None)
    };

    let release_namespace_hint = options
        .release_namespace_hint
        .or_else(|| release.as_ref().map(|release| release.metadata.namespace.as_str()));

    if options.resolve_namespaces && should_resolve_namespaces(&manifests, options.offline) {
        let client = kube_client
            .as_ref()
            .expect("kube client must exist when namespace resolution is enabled");
        resolve_manifest_namespaces(client, &mut manifests, release_namespace_hint).await?;
    }

    if options.adjust_duplicate_keys {
        if let Some(client) = kube_client.as_ref() {
            duplicates =
                adjust_duplicate_keys_for_namespace_resolution(client, &duplicates, release_namespace_hint).await?;
        }
    }

    Ok(RenderPreflightResult {
        manifests,
        release,
        strip_empty_metadata_labels,
        resolved_target,
        duplicates,
        kube_client,
        raw_client,
    })
}

pub async fn execute(args: RenderArgs) -> Result<()> {
    if !args.offline && (args.kube_version.is_some() || !args.kube_api_versions.is_empty()) {
        return Err(NylError::config(
            "--kube-version and --kube-api-versions require --offline",
        ));
    }
    let preflight = run_render_preflight(RenderPreflightOptions {
        common: &args.common,
        offline: args.offline,
        kube_version: args.kube_version.as_deref(),
        kube_api_versions: &args.kube_api_versions,
        context_override: args.context.as_deref(),
        cluster_client_requirement: ClusterClientRequirement::OnDemand,
        resolve_namespaces: true,
        release_namespace_hint: None,
        adjust_duplicate_keys: false,
    })
    .await?;

    // Print duplicate warning summary if any
    if !preflight.duplicates.is_empty() {
        let total_unique = preflight.duplicates.len();
        let total_ignored: usize = preflight.duplicates.values().map(|count| count - 1).sum();
        tracing::warn!(
            "Found {} unique resources with duplicates ({} total duplicates ignored, keeping last occurrence)",
            total_unique,
            total_ignored
        );
    }

    output_manifests(
        &preflight.manifests,
        OutputFormat::Yaml,
        preflight.strip_empty_metadata_labels,
    )?;
    Ok(())
}

pub(crate) fn should_resolve_namespaces(manifests: &[serde_json::Value], offline: bool) -> bool {
    !offline && manifests.iter().any(manifest_requires_namespace_resolution)
}

pub(crate) fn should_initialize_cluster_clients(
    offline: bool,
    cluster_client_requirement: ClusterClientRequirement,
    resolve_namespaces: bool,
    manifests: &[serde_json::Value],
    adjust_duplicate_keys: bool,
) -> bool {
    !offline
        && (cluster_client_requirement == ClusterClientRequirement::Required
            || adjust_duplicate_keys
            || (resolve_namespaces && should_resolve_namespaces(manifests, offline)))
}

fn manifest_requires_namespace_resolution(manifest: &serde_json::Value) -> bool {
    let has_namespace = crate::kubernetes::extract_namespace(manifest)
        .as_deref()
        .is_some_and(|ns| !ns.trim().is_empty());
    if has_namespace {
        return false;
    }

    crate::kubernetes::extract_gvk(manifest).map_or(true, |gvk| !crate::kubernetes::is_known_cluster_scoped_gvk(&gvk))
}

// Note: parse_yaml_documents is now replaced by SourceContext::parse_yaml_documents
/// (i.e. it is a HelmChart or Component, not a plain k8s manifest)
fn output_manifests(
    manifests: &[serde_json::Value],
    format: OutputFormat,
    strip_empty_metadata_labels: bool,
) -> Result<()> {
    let manifests = prepare_manifests_for_output(manifests, strip_empty_metadata_labels);

    match format {
        OutputFormat::Yaml => {
            for (i, manifest) in manifests.iter().enumerate() {
                if i > 0 {
                    println!("---");
                }
                let yaml = crate::yaml::serialize_yaml_document(manifest).map_err(NylError::YamlEmit)?;
                print!("{}", yaml);
            }
        }
        OutputFormat::Json => {
            let json = serde_json::to_string_pretty(&manifests)
                .map_err(|e| NylError::Config(format!("Failed to serialize JSON: {}", e)))?;
            println!("{}", json);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_resolve_namespaces_online_with_missing_namespace() {
        let manifests = vec![serde_json::json!({
            "apiVersion": "v1",
            "kind": "ServiceAccount",
            "metadata": {"name": "sa"}
        })];
        assert!(should_resolve_namespaces(&manifests, false));
    }

    #[test]
    fn test_should_not_resolve_namespaces_offline() {
        let manifests = vec![serde_json::json!({
            "apiVersion": "v1",
            "kind": "ServiceAccount",
            "metadata": {"name": "sa"}
        })];
        assert!(!should_resolve_namespaces(&manifests, true));
    }

    #[test]
    fn test_should_not_resolve_namespaces_when_all_namespaces_present() {
        let manifests = vec![serde_json::json!({
            "apiVersion": "v1",
            "kind": "ServiceAccount",
            "metadata": {"name": "sa", "namespace": "default"}
        })];
        assert!(!should_resolve_namespaces(&manifests, false));
    }

    #[test]
    fn test_should_not_resolve_namespaces_for_known_cluster_scoped_resources() {
        let manifests = vec![serde_json::json!({
            "apiVersion": "v1",
            "kind": "Namespace",
            "metadata": {"name": "infra"}
        })];
        assert!(!should_resolve_namespaces(&manifests, false));
    }

    #[test]
    fn test_should_initialize_cluster_clients_offline() {
        assert!(!should_initialize_cluster_clients(
            true,
            ClusterClientRequirement::Required,
            true,
            &[],
            true
        ));
    }

    #[test]
    fn test_should_initialize_cluster_clients_required() {
        assert!(should_initialize_cluster_clients(
            false,
            ClusterClientRequirement::Required,
            false,
            &[],
            false
        ));
    }

    #[test]
    fn test_should_initialize_cluster_clients_for_namespace_resolution() {
        let manifests = vec![serde_json::json!({
            "apiVersion": "v1",
            "kind": "ServiceAccount",
            "metadata": {"name": "sa"}
        })];

        assert!(should_initialize_cluster_clients(
            false,
            ClusterClientRequirement::OnDemand,
            true,
            &manifests,
            false
        ));
    }

    #[test]
    fn test_should_not_initialize_cluster_clients_for_cluster_scoped_resources() {
        let manifests = vec![serde_json::json!({
            "apiVersion": "v1",
            "kind": "Namespace",
            "metadata": {"name": "infra"}
        })];

        assert!(!should_initialize_cluster_clients(
            false,
            ClusterClientRequirement::OnDemand,
            true,
            &manifests,
            false
        ));
    }

    #[test]
    fn test_should_not_initialize_cluster_clients_when_not_needed() {
        let manifests = vec![serde_json::json!({
            "apiVersion": "v1",
            "kind": "ServiceAccount",
            "metadata": {"name": "sa", "namespace": "default"}
        })];

        assert!(!should_initialize_cluster_clients(
            false,
            ClusterClientRequirement::OnDemand,
            true,
            &manifests,
            false
        ));
    }

    #[test]
    fn test_should_initialize_cluster_clients_for_duplicate_adjustment() {
        assert!(should_initialize_cluster_clients(
            false,
            ClusterClientRequirement::OnDemand,
            false,
            &[],
            true
        ));
    }
}
