#
# This is an example Kubernetes manifest that can be applied with Nyl to deploy ArgoCD with Nyl as a Config Management
# Plugin.
#

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-nyl-env
  namespace: argocd
type: Opaque
stringData:
  SOPS_AGE_KEY: ${{ secrets.get("SOPS_AGE_KEY") }}

---
apiVersion: inline.nyl.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: argocd
spec:
  chart:
    # Explore the chart at https://artifacthub.io/packages/helm/argo/argo-cd
    repository: https://argoproj.github.io/argo-helm
    name: argo-cd
    version: "7.4.3"
  values:
    configs:
      secret:
        argocdServerAdminPassword: ${{ bcrypt(secrets.get("ARGOCD_ADMIN_PASSWORD")) }}
    dex:
      enabled: false
    repoServer:
      extraContainers:
        - name: nyl-v1
          # NOTE: This image uses the Rust version of Nyl (SOPS not yet implemented)
          image: ghcr.io/niklasrosenstein/nyl:1.0.0
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: cmp-tmp
          env:
            - name: NYL_CACHE_DIR
              value: /tmp/nyl
          envFrom:
            - secretRef:
                name: argocd-nyl-env
      volumes:
        - name: cmp-tmp
          emptyDir: {}

      # HACK: Allow argocd-repo-server to read all Kubernetes resources. This is used by Helm and Nyl lookups.
      #       However, this only works in-cluster and not with other clusters.
      clusterRoleRules:
        enabled: true

# Self-manage ArgoCD with Nyl and this specific repository.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/helsing-ai/nyl.git
    targetRevision: HEAD
    path: argocd-with-nyl
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
