site_name: nyl
repo_name: nyl
repo_url: https://git.rosenstein.app/niklas/nyl.git
docs_dir: content
theme:
  name: material
  palette:
    accent: blue
    primary: purple
    scheme: default
  features:
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.sections
    - toc.follow
    # - toc.integrate
markdown_extensions:
- admonition
# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details

plugins:
- search
- mkdocstrings
