# HTTP chart without version (uses latest from Bitnami)
apiVersion: components.nyl.niklasrosenstein.github.com/v1
kind: https://charts.bitnami.com/bitnami#redis
metadata:
  name: my-redis
  namespace: default
spec:
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
