# OCI registry example (cert-manager from Jetstack)
apiVersion: components.nyl.niklasrosenstein.github.com/v1
kind: oci://registry-1.docker.io/bitnamicharts/nginx@18.2.4
metadata:
  name: nginx-oci
  namespace: default
spec:
  replicaCount: 1
  service:
    type: ClusterIP
