name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        step: ["pytest", "ruff format --check", "ruff check"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install PDM
        run: python -m pip install --upgrade pdm

      - name: Install project
        run: pdm install

      - name: Run ${{ matrix.step }}
        run: pdm run -- ${{ matrix.step }}

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install PDM
        run: python -m pip install --upgrade pdm

      - name: Inject version number ${{ github.ref_name }} into pyproject.toml
        run: sed -i "s/version = .*/version = \"${{ github.ref_name }}\"/" pyproject.toml

      - name: Build the package
        run: pdm build

      - name: Publish package
        run: pdm publish --no-build -u __token__ -p ${{ secrets.PYPI_PASSWORD }}
