name: Publish Crates.io

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' || !github.event.release.prerelease }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish nyl to crates.io
        run: cargo publish -p nyl --locked
